### ISSUE TITLE
Warning are thrown for 'stty size'

### ISSUE THREAD

**Issue by yassine-ah** [sebastianbergmann/environment#35]
PHP Warning in Environment that forbidden `stty` command:

```
demo-5b72bc:~$ php vendor/phpunit/phpunit/phpunit tests/Unit/ExampleTest.php
PHP Warning:  shell_exec(): Unable to execute 'stty size' in /var/www/demo/vendor/sebastian/environment/src/Console.php on line 93
PHP Fatal error:  Uncaught TypeError: preg_match() expects parameter 2 to be string, boolean given in /var/www/demo/vendor/sebastian/environment/src/Console.php:93
Stack trace:
#0 /var/www/demo/vendor/sebastian/environment/src/Console.php(93): preg_match('#\\d+ (\\d+)#', false, NULL)
#1 /var/www/demo/vendor/sebastian/environment/src/Console.php(70): SebastianBergmann\Environment\Console->getNumberOfColumnsInteractive()
#2 /var/www/demo/vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(173): SebastianBergmann\Environment\Console->getNumberOfColumns()
#3 /var/www/demo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(287): PHPUnit\TextUI\ResultPrinter->__construct(NULL, false, 'auto', false, 80, false)
#4 /var/www/demo/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#5 /var/www/demo/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->ru in /var/www/demo/vendor/sebastian/environment/src/Console.php on line 93
```

It is somewhat similar to #16

**Comment by sebastianbergmann** [comment]
How is `stty` forbidden?

**Comment by rob-gonz** [comment]
I'm curious if anyone has figured this out. I"m encountering this in an environment I'm trying to set up to run unit tests.   If I create my own `test.php` file with `shell_exec('stty size`);` it works fine.  But, the one in the Console.php file throws the same error as OP.

**Comment by joshdavis11** [comment]
I'm seeing the same issue
```shell
Error number 2 (WARNING): shell_exec(): Unable to execute 'stty size'
on line 93 of /vagrant/vendor/sebastian/environment/src/Console.php
```

I'm running an ubuntu vagrant box on Mac OS X 10.15.3. I only see it occasionally, however, and a `vagrant halt` + `vagrant up` seems to fix it for a while. The odd part, though, like @rob-gonz is that I can run php interactively and it's fine
```shell
vagrant@vagrant:/vagrant/tests$ php -a
Interactive mode enabled

php > echo shell_exec('stty size');
58 204
php >
```
as well as make a test file and run the test file 
```php
<?php
//test.php
echo shell_exec('stty size');
```

```shell
vagrant@vagrant-appdev:/vagrant/tests$ vim test.php
vagrant@vagrant-appdev:/vagrant/tests$ php test.php
58 204
```
